// examples/solid-lib/src/components/Button.tsx
import { Component, JSX, splitProps } from 'solid-js'
import './Button.less'

export interface ButtonProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
  type?: 'primary' | 'default' | 'danger'
  size?: 'small' | 'medium' | 'large'
}

export const Button: Component<ButtonProps> = (props) => {
  const [local, others] = splitProps(props, ['type', 'size', 'class', 'children'])
  
  const buttonClasses = () => [
    'ldesign-button',
    `ldesign-button--${local.type || 'default'}`,
    `ldesign-button--${local.size || 'medium'}`,
    local.class
  ].filter(Boolean).join(' ')

  return (
    <button class={buttonClasses()} {...others}>
      {local.children}
    </button>
  )
}

// examples/preact-lib/src/components/Button.tsx
import { h, FunctionComponent } from 'preact'
import './Button.less'

export interface ButtonProps {
  type?: 'primary' | 'default' | 'danger'
  size?: 'small' | 'medium' | 'large'
  disabled?: boolean
  onClick?: (event: MouseEvent) => void
  children?: any
}

export const Button: FunctionComponent<ButtonProps> = ({
  type = 'default',
  size = 'medium',
  disabled = false,
  onClick,
  children
}) => {
  const buttonClasses = [
    'ldesign-button',
    `ldesign-button--${type}`,
    `ldesign-button--${size}`,
    disabled && 'ldesign-button--disabled'
  ].filter(Boolean).join(' ')

  return (
    <button class={buttonClasses} disabled={disabled} onClick={onClick}>
      {children}
    </button>
  )
}
