// examples/react-lib/src/components/Button/index.tsx
import React from 'react'
import './style.less'

export interface ButtonProps {
  /**
   * 按钮类型
   */
  type?: 'primary' | 'default' | 'danger'
  
  /**
   * 按钮大小
   */
  size?: 'small' | 'medium' | 'large'
  
  /**
   * 是否禁用
   */
  disabled?: boolean
  
  /**
   * 按钮文本
   */
  children?: React.ReactNode
  
  /**
   * 点击事件
   */
  onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void
  
  /**
   * 自定义类名
   */
  className?: string
}

/**
 * Button 组件
 */
export const Button: React.FC<ButtonProps> = ({
  type = 'default',
  size = 'medium',
  disabled = false,
  children,
  onClick,
  className = ''
}) => {
  const classNames = [
    'ldesign-button',
    `ldesign-button--${type}`,
    `ldesign-button--${size}`,
    disabled && 'ldesign-button--disabled',
    className
  ].filter(Boolean).join(' ')

  return (
    <button
      className={classNames}
      disabled={disabled}
      onClick={onClick}
    >
      {children}
    </button>
  )
}

Button.displayName = 'Button'

// examples/solid-lib/src/components/Button.tsx
import { Component, JSX, splitProps } from 'solid-js'
import './Button.less'

export interface ButtonProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
  type?: 'primary' | 'default' | 'danger'
  size?: 'small' | 'medium' | 'large'
}

export const Button: Component<ButtonProps> = (props) => {
  const [local, others] = splitProps(props, ['type', 'size', 'class', 'children'])
  
  const buttonClasses = () => [
    'ldesign-button',
    `ldesign-button--${local.type || 'default'}`,
    `ldesign-button--${local.size || 'medium'}`,
    local.class
  ].filter(Boolean).join(' ')

  return (
    <button class={buttonClasses()} {...others}>
      {local.children}
    </button>
  )
}
