// examples/qwik-lib/src/components/input.tsx
import { component$, type QwikIntrinsicElements } from '@builder.io/qwik'
import './input.less'

export interface InputProps extends QwikIntrinsicElements['input'] {
  size?: 'small' | 'medium' | 'large'
}

export const Input = component$<InputProps>(({ size = 'medium', ...props }) => {
  const inputClasses = [
    'ldesign-input',
    `ldesign-input--${size}`,
    props.disabled && 'ldesign-input--disabled'
  ].filter(Boolean).join(' ')

  return <input class={inputClasses} {...props} />
})

// examples/solid-lib/src/components/Input.tsx
import { Component, JSX, splitProps } from 'solid-js'
import './Input.less'

export interface InputProps extends JSX.InputHTMLAttributes<HTMLInputElement> {
  size?: 'small' | 'medium' | 'large'
}

export const Input: Component<InputProps> = (props) => {
  const [local, others] = splitProps(props, ['size', 'class'])
  
  const inputClasses = () => [
    'ldesign-input',
    `ldesign-input--${local.size || 'medium'}`,
    local.class
  ].filter(Boolean).join(' ')

  return <input class={inputClasses()} {...others} />
}
