// examples/svelte-lib/src/card/Card.svelte
<script>
  /** @type {string} */
  export let title = ''
  /** @type {boolean} */
  export let bordered = true
  /** @type {boolean} */
  export let shadow = false
</script>

<div
  class="card"
  class:bordered
  class:shadow
>
  {#if title}
    <div class="card-header">
      <h3 class="card-title">{title}</h3>
      <slot name="extra" />
    </div>
  {/if}
  <div class="card-body">
    <slot />
  </div>
  {#if $$slots.footer}
    <div class="card-footer">
      <slot name="footer" />
    </div>
  {/if}
</div>

<style>
  .card {
    background: white;
    border-radius: 8px;
    overflow: hidden;
  }
  
  .bordered {
    border: 1px solid #e5e7eb;
  }
  
  .shadow {
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
  }
  
  .card-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 16px;
    border-bottom: 1px solid #e5e7eb;
  }
  
  .card-title {
    margin: 0;
    font-size: 16px;
    font-weight: 600;
  }
  
  .card-body {
    padding: 16px;
  }
  
  .card-footer {
    padding: 12px 16px;
    border-top: 1px solid #e5e7eb;
    background: #f9fafb;
  }
</style>

// examples/solid-lib/src/card/index.tsx
/**
 * Solid.js Card Component
 */
import { Component, JSX, splitProps, Show } from 'solid-js'

export interface CardProps extends JSX.HTMLAttributes<HTMLDivElement> {
  title?: string
  bordered?: boolean
  shadow?: boolean
  children?: JSX.Element
  footer?: JSX.Element
  extra?: JSX.Element
}

export const Card: Component<CardProps> = (props) => {
  const [local, rest] = splitProps(props, [
    'title',
    'bordered',
    'shadow',
    'children',
    'footer',
    'extra',
    'class'
  ])

  const cardClasses = () => {
    const classes = ['bg-white rounded-lg overflow-hidden']
    if (local.bordered) classes.push('border border-gray-200')
    if (local.shadow) classes.push('shadow-md')
    if (local.class) classes.push(local.class)
    return classes.join(' ')
  }

  return (
    <div {...rest} class={cardClasses()}>
      <Show when={local.title}>
        <div class="flex items-center justify-between px-4 py-3 border-b border-gray-200">
          <h3 class="text-lg font-semibold text-gray-900">{local.title}</h3>
          <Show when={local.extra}>
            <div>{local.extra}</div>
          </Show>
        </div>
      </Show>

      <div class="p-4">
        {local.children}
      </div>

      <Show when={local.footer}>
        <div class="px-4 py-3 bg-gray-50 border-t border-gray-200">
          {local.footer}
        </div>
      </Show>
    </div>
  )
}
