// examples/mixed-framework/src/vue/Card.vue.tsx
/**
 * Vue Card 组件（使用 TSX）
 */

import { defineComponent, type PropType } from 'vue'
import type { CardProps } from '../shared/types'

export default defineComponent({
  name: 'VueCard',

  props: {
    title: {
      type: String,
      required: true
    },
    bordered: {
      type: Boolean,
      default: true
    },
    hoverable: {
      type: Boolean,
      default: false
    }
  },

  emits: ['click'],

  setup(props, { slots, emit }) {
    const handleClick = (event: MouseEvent) => {
      if (props.hoverable) {
        emit('click', event)
      }
    }

    return () => (
      <div
        class={{
          'card': true,
          'card--bordered': props.bordered,
          'card--hoverable': props.hoverable
        }}
        onClick={handleClick}
      >
        <div class="card__header">
          <h3 class="card__title">{props.title}</h3>
        </div>
        <div class="card__body">
          {slots.default?.()}
        </div>
        {slots.footer && (
          <div class="card__footer">
            {slots.footer()}
          </div>
        )}
      </div>
    )
  }
})

// examples/mixed-framework/src/react/Card.react.tsx
/**
 * React Card 组件
 */

import React, { type FC, type MouseEvent, type ReactNode } from 'react'
import type { CardProps } from '../shared/types'

interface ReactCardProps extends CardProps {
  children: ReactNode
  footer?: ReactNode
}

export const ReactCard: FC<ReactCardProps> = ({
  title,
  bordered = true,
  hoverable = false,
  onClick,
  children,
  footer
}) => {
  const handleClick = (event: MouseEvent<HTMLDivElement>) => {
    if (hoverable && onClick) {
      onClick(event)
    }
  }

  const classNames = [
    'card',
    bordered && 'card--bordered',
    hoverable && 'card--hoverable'
  ].filter(Boolean).join(' ')

  return (
    <div className={classNames} onClick={handleClick}>
      <div className="card__header">
        <h3 className="card__title">{title}</h3>
      </div>
      <div className="card__body">
        {children}
      </div>
      {footer && (
        <div className="card__footer">
          {footer}
        </div>
      )}
    </div>
  )
}

ReactCard.displayName = 'ReactCard'
