// examples/solid-lib/src/hooks/index.ts
/**
 * Solid.js Custom Hooks
 */
import { createSignal, Accessor } from 'solid-js'

/**
 * Toggle hook - 创建一个可切换的布尔值状态
 */
export function createToggle(initialValue = false): [Accessor<boolean>, () => void, (value: boolean) => void] {
  const [value, setValue] = createSignal(initialValue)

  const toggle = () => setValue(v => !v)
  const set = (newValue: boolean) => setValue(newValue)

  return [value, toggle, set]
}

/**
 * Counter hook - 创建一个计数器状态
 */
export function createCounter(initialValue = 0, step = 1) {
  const [count, setCount] = createSignal(initialValue)

  const increment = () => setCount(c => c + step)
  const decrement = () => setCount(c => c - step)
  const reset = () => setCount(initialValue)
  const set = (value: number) => setCount(value)

  return {
    count,
    increment,
    decrement,
    reset,
    set
  }
}

/**
 * LocalStorage hook - 持久化存储
 */
export function createLocalStorage<T>(key: string, initialValue: T) {
  const stored = localStorage.getItem(key)
  const initial = stored ? JSON.parse(stored) : initialValue

  const [value, setValue] = createSignal<T>(initial)

  const set = (newValue: T | ((prev: T) => T)) => {
    const resolvedValue = typeof newValue === 'function'
      ? (newValue as (prev: T) => T)(value())
      : newValue
    setValue(() => resolvedValue)
    localStorage.setItem(key, JSON.stringify(resolvedValue))
  }

  const remove = () => {
    localStorage.removeItem(key)
    setValue(() => initialValue)
  }

  return [value, set, remove] as const
}

// examples/mixed-framework/src/react/hooks.ts
/**
 * React Hooks
 */

import { useState, useCallback, useEffect, useRef } from 'react'

/**
 * 计数器 hook
 */
export function useCounter(initialValue = 0) {
  const [count, setCount] = useState(initialValue)

  const increment = useCallback(() => {
    setCount(c => c + 1)
  }, [])

  const decrement = useCallback(() => {
    setCount(c => c - 1)
  }, [])

  const reset = useCallback(() => {
    setCount(initialValue)
  }, [initialValue])

  const doubled = count * 2

  return {
    count,
    doubled,
    increment,
    decrement,
    reset
  }
}

/**
 * 本地存储 hook
 */
export function useLocalStorage<T>(
  key: string,
  defaultValue: T
): [T, (value: T) => void] {
  const [value, setValue] = useState<T>(() => {
    try {
      const item = localStorage.getItem(key)
      return item ? JSON.parse(item) : defaultValue
    } catch {
      return defaultValue
    }
  })

  const setStoredValue = useCallback((newValue: T) => {
    setValue(newValue)
    localStorage.setItem(key, JSON.stringify(newValue))
  }, [key])

  return [value, setStoredValue]
}

/**
 * 防抖 hook
 */
export function useDebounce<T>(value: T, delay: number): T {
  const [debouncedValue, setDebouncedValue] = useState(value)

  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedValue(value)
    }, delay)

    return () => {
      clearTimeout(timer)
    }
  }, [value, delay])

  return debouncedValue
}
